import 'dart:async';
import 'package:flutter/material.dart';
import '../../services/api_service.dart';
import '../chat/chat_screen.dart';

class TrackServiceScreen extends StatefulWidget {
  final String? bookingId;
  final Map<String, dynamic>? booking;

  const TrackServiceScreen({
    super.key,
    this.bookingId,
    this.booking,
  });

  @override
  State<TrackServiceScreen> createState() => _TrackServiceScreenState();
}

class _TrackServiceScreenState extends State<TrackServiceScreen> {
  Map<String, dynamic>? _bookingData;
  List<dynamic> _notifications = [];
  Timer? _pollingTimer;
  bool _isLoading = false;
  String? _errorMessage;

  @override
  void initState() {
    super.initState();
    _bookingData = widget.booking;
    if (_bookingData == null) {
      _isLoading = true;
    }
    _fetchBookingAndNotifications();
    // Refresh every 5 seconds while tracking screen is open
    _pollingTimer = Timer.periodic(const Duration(seconds: 5), (_) {
      _fetchBookingAndNotifications();
    });
  }

  @override
  void dispose() {
    _pollingTimer?.cancel();
    super.dispose();
  }

  Future<void> _fetchBookingAndNotifications() async {
    final bId = widget.bookingId ?? _bookingData?['_id'] ?? _bookingData?['id'];
    if (bId == null || bId.toString().isEmpty) {
      if (mounted) {
        setState(() {
          _isLoading = false;
          _errorMessage = 'Booking ID not provided.';
        });
      }
      return;
    }

    try {
      final updatedBooking = await ApiService.getBookingById(bId.toString());
      final notifications = await ApiService.getNotifications();
      if (mounted) {
        setState(() {
          if (updatedBooking != null) {
            _bookingData = updatedBooking;
            _errorMessage = null;
          } else if (_bookingData == null) {
            _errorMessage = 'Unable to fetch booking status. Please check your connection and retry.';
          }
          _notifications = notifications;
          _isLoading = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          if (_bookingData == null) {
            _errorMessage = 'Error loading tracking details: $e';
          }
          _isLoading = false;
        });
      }
    }
  }

  // Extract OTP from notifications if generated by backend
  String? _getOtpFromNotifications(String type) {
    if (_notifications.isEmpty) return null;
    final searchKey = type == 'start' ? 'Start OTP' : 'End OTP';

    for (final notif in _notifications) {
      if (notif == null || notif is! Map) continue;
      final title = notif['title']?.toString() ?? '';
      final message = notif['message']?.toString() ?? '';

      if (title.contains(searchKey) || message.contains(searchKey)) {
        // Extract 6-digit number
        final match = RegExp(r'\b\d{6}\b').firstMatch(message);
        if (match != null) {
          return match.group(0);
        }
      }
    }
    return null;
  }

  int _calculateCurrentStep(String status) {
    final s = status.toLowerCase().trim();
    if (s.contains('complete') || s.contains('closed') || s.contains('done') || s.contains('finalised')) {
      return 6;
    }
    if (s == 'waiting_end_otp' || s.contains('end_otp') || s.contains('verify')) {
      return 5;
    }
    if (s == 'in_progress' || s == 'started' || s.contains('progress')) {
      return 4;
    }
    if (s == 'arrived' || s == 'waiting_start_otp' || s.contains('arriv') || s.contains('reach')) {
      return 3;
    }
    if (s == 'on_the_way' || s.contains('way')) {
      return 2;
    }
    if (s == 'accepted' || s == 'assigned' || s.contains('accept') || s.contains('assign')) {
      return 1;
    }
    if (s == 'pending' || s == 'provider_searching' || s.contains('search')) {
      return 0;
    }
    return 1;
  }

  void _makePhoneCall(String? phoneNumber) {
    if (phoneNumber == null || phoneNumber.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Phone number not available for this provider.'),
          backgroundColor: Colors.orange,
        ),
      );
      return;
    }
    try {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Calling professional: $phoneNumber')),
      );
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Unable to initiate call: $e'), backgroundColor: Colors.red),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading && _bookingData == null) {
      return Scaffold(
        backgroundColor: const Color(0xFFFAFAFA),
        appBar: AppBar(
          title: const Text('Track Service', style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold)),
          backgroundColor: Colors.white,
          elevation: 0,
          leading: IconButton(
            icon: const Icon(Icons.arrow_back_ios_new, size: 20, color: Colors.black),
            onPressed: () => Navigator.pop(context),
          ),
        ),
        body: const Center(child: CircularProgressIndicator()),
      );
    }

    if (_errorMessage != null && _bookingData == null) {
      return Scaffold(
        backgroundColor: const Color(0xFFFAFAFA),
        appBar: AppBar(
          title: const Text('Track Service', style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold)),
          backgroundColor: Colors.white,
          elevation: 0,
          leading: IconButton(
            icon: const Icon(Icons.arrow_back_ios_new, size: 20, color: Colors.black),
            onPressed: () => Navigator.pop(context),
          ),
        ),
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(24.0),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const Icon(Icons.error_outline, size: 60, color: Colors.redAccent),
                const SizedBox(height: 16),
                Text(
                  _errorMessage!,
                  textAlign: TextAlign.center,
                  style: const TextStyle(fontSize: 16, color: Colors.black87),
                ),
                const SizedBox(height: 24),
                ElevatedButton.icon(
                  onPressed: () {
                    setState(() {
                      _isLoading = true;
                      _errorMessage = null;
                    });
                    _fetchBookingAndNotifications();
                  },
                  icon: const Icon(Icons.refresh),
                  label: const Text('Retry'),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFF1B1464),
                    foregroundColor: Colors.white,
                  ),
                ),
              ],
            ),
          ),
        ),
      );
    }

    final status = (_bookingData?['status'] ??
                    _bookingData?['booking_status'] ??
                    _bookingData?['booking']?['status'] ??
                    _bookingData?['data']?['status'] ??
                    'pending').toString().toLowerCase().trim();
    final currentStep = _calculateCurrentStep(status);
    final isArrived = status == 'arrived' || status == 'waiting_start_otp' || currentStep >= 3;

    // Provider Info
    final providerMap = _bookingData?['provider_id'];
    String providerName = 'Searching for Provider...';
    String providerProfession = 'Service Partner';
    String providerRating = 'N/A';
    String providerPhone = '';

    if (providerMap != null && providerMap is Map) {
      final pUser = providerMap['user_id'];
      if (pUser != null && pUser is Map) {
        providerName = pUser['name'] ?? pUser['fullName'] ?? pUser['phone'] ?? 'Assigned Professional';
        providerPhone = pUser['phone']?.toString() ?? '';
      } else if (providerMap['name'] != null) {
        providerName = providerMap['name'].toString();
      } else {
        providerName = 'Assigned Professional';
      }

      providerProfession = providerMap['profession'] ?? providerMap['service'] ?? 'Service Partner';
      
      final rawRating = providerMap['rating'] ?? providerMap['avgRating'] ?? providerMap['ratingAverage'];
      if (rawRating != null && rawRating.toString().isNotEmpty) {
        final double? parsedRating = double.tryParse(rawRating.toString());
        if (parsedRating != null) {
          providerRating = parsedRating.toStringAsFixed(1);
        } else {
          providerRating = rawRating.toString();
        }
      } else {
        providerRating = '5.0';
      }
    }

    final startOtp = _getOtpFromNotifications('start');
    final endOtp = _getOtpFromNotifications('end');

    return Scaffold(
      backgroundColor: const Color(0xFFFAFAFA),
      body: SafeArea(
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _buildHeader(context),
              const SizedBox(height: 16),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 20.0),
                child: _buildServiceDetailsCard(),
              ),
              const SizedBox(height: 12),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 20.0),
                child: _buildProfessionalBanner(
                  name: providerName,
                  profession: providerProfession,
                  rating: providerRating,
                  phone: providerPhone,
                  status: status,
                  isArrived: isArrived,
                ),
              ),
              const SizedBox(height: 24),
              const Padding(
                padding: EdgeInsets.symmetric(horizontal: 20.0),
                child: Text(
                  'Service Status',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                    color: Color(0xFF1B1464),
                  ),
                ),
              ),
              const SizedBox(height: 16),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 20.0),
                child: _buildTimeline(
                  currentStep: currentStep,
                  status: status,
                  startOtp: startOtp,
                  endOtp: endOtp,
                ),
              ),
              const SizedBox(height: 32),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildHeader(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.fromLTRB(20, 20, 20, 0),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Row(
            children: [
              GestureDetector(
                onTap: () => Navigator.pop(context),
                child: const Icon(Icons.arrow_back_ios_new, size: 20, color: Colors.black87),
              ),
              const SizedBox(width: 16),
              const Text(
                'Track Service',
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: Colors.black87,
                ),
              ),
            ],
          ),
          IconButton(
            icon: const Icon(Icons.refresh, color: Color(0xFF1B1464)),
            onPressed: () {
              _fetchBookingAndNotifications();
            },
          ),
        ],
      ),
    );
  }

  Widget _buildServiceDetailsCard() {
    if (_bookingData == null) return const SizedBox.shrink();

    final subservice = _bookingData!['subservice_id'];
    String serviceName = 'Service Request';
    if (subservice != null && subservice is Map) {
      serviceName = (subservice['subservice_name'] ?? subservice['name'] ?? 'Service').toString();
    } else if (_bookingData!['service_name'] != null && _bookingData!['service_name'].toString().isNotEmpty) {
      serviceName = _bookingData!['service_name'].toString();
    } else if (_bookingData!['title'] != null) {
      serviceName = _bookingData!['title'].toString();
    }

    final bookingIdStr = _bookingData!['booking_id'] ?? _bookingData!['_id'] ?? '#---';
    final payableAmount = (_bookingData!['payable_amount'] ?? _bookingData!['total_amount'] ?? '0').toString();
    final bookingDate = _bookingData!['booking_date']?.toString() ?? _bookingData!['scheduled_at']?.toString() ?? '';
    final bookingTime = _bookingData!['booking_time']?.toString() ?? _bookingData!['slot']?.toString() ?? '';

    String formattedSchedule = '';
    if (bookingDate.isNotEmpty) {
      formattedSchedule = bookingTime.isNotEmpty ? '$bookingDate • $bookingTime' : bookingDate;
    } else if (bookingTime.isNotEmpty) {
      formattedSchedule = bookingTime;
    }

    String addressText = '';
    final addrObj = _bookingData!['address_id'];
    if (addrObj is Map) {
      final line1 = (addrObj['address_line'] ?? addrObj['address_line_1'] ?? addrObj['area_locality'] ?? '').toString();
      final city = (addrObj['city'] ?? '').toString();
      final pincode = (addrObj['pincode'] ?? '').toString();
      addressText = [line1, city, pincode].where((s) => s.isNotEmpty).join(', ');
    } else if (addrObj is String && addrObj.isNotEmpty) {
      addressText = addrObj;
    } else if (_bookingData!['address'] != null) {
      addressText = _bookingData!['address'].toString();
    }

    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.grey.shade200),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.04),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(10),
                decoration: BoxDecoration(
                  color: const Color(0xFFEFF1FE),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: const Icon(Icons.handyman_outlined, color: Color(0xFF1B1464), size: 24),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      serviceName,
                      style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: Color(0xFF1B1464)),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      'Ref ID: $bookingIdStr',
                      style: TextStyle(fontSize: 11, color: Colors.grey.shade500),
                    ),
                  ],
                ),
              ),
              Text(
                '₹$payableAmount',
                style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Color(0xFF1B1464)),
              ),
            ],
          ),
          if (formattedSchedule.isNotEmpty) ...[
            const Divider(height: 20),
            Row(
              children: [
                const Icon(Icons.calendar_today_outlined, size: 14, color: Colors.black54),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(
                    formattedSchedule,
                    style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w600, color: Colors.black87),
                  ),
                ),
              ],
            ),
          ],
          if (addressText.isNotEmpty) ...[
            const SizedBox(height: 6),
            Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Icon(Icons.location_on_outlined, size: 14, color: Colors.black54),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(
                    addressText,
                    style: TextStyle(fontSize: 12, color: Colors.grey.shade700),
                    maxLines: 2,
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
              ],
            ),
          ],
        ],
      ),
    );
  }

  Widget _buildProfessionalBanner({
    required String name,
    required String profession,
    required String rating,
    required String phone,
    required String status,
    required bool isArrived,
  }) {
    final s = status.toLowerCase().trim();
    String statusLabel = 'Searching...';
    Color pillBg = const Color(0xFFE8E8FF);
    Color pillText = const Color(0xFF1B1464);

    if (s.contains('complete') || s.contains('closed') || s.contains('done') || s.contains('finalised')) {
      statusLabel = 'Service Completed';
      pillBg = Colors.green.shade100;
      pillText = Colors.green.shade900;
    } else if (s == 'waiting_end_otp' || s.contains('end_otp') || s.contains('verify')) {
      statusLabel = 'Verification';
      pillBg = Colors.amber.shade100;
      pillText = Colors.amber.shade900;
    } else if (s == 'in_progress' || s == 'started' || s.contains('progress')) {
      statusLabel = 'In Progress';
      pillBg = Colors.purple.shade100;
      pillText = Colors.purple.shade900;
    } else if (s == 'arrived' || s == 'waiting_start_otp' || s.contains('arriv') || s.contains('reach')) {
      statusLabel = 'Arrived';
      pillBg = Colors.amber.shade100;
      pillText = Colors.amber.shade900;
    } else if (s == 'on_the_way' || s.contains('way')) {
      statusLabel = 'On the Way';
      pillBg = Colors.blue.shade100;
      pillText = Colors.blue.shade900;
    } else if (s == 'accepted' || s == 'assigned' || s.contains('accept') || s.contains('assign')) {
      statusLabel = 'Assigned';
      pillBg = const Color(0xFFE8E8FF);
      pillText = const Color(0xFF1B1464);
    }

    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.grey.shade200),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.04),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        children: [
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              ClipOval(
                child: Container(
                  width: 48,
                  height: 48,
                  color: Colors.grey.shade200,
                  child: const Icon(Icons.person, color: Colors.grey),
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      name,
                      style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: Colors.black87),
                    ),
                    const SizedBox(height: 4),
                    Row(
                      children: [
                        Icon(Icons.star, color: Colors.amber.shade600, size: 14),
                        const SizedBox(width: 4),
                        Text(rating, style: const TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: Colors.black87)),
                        const SizedBox(width: 4),
                        Text('• $profession', style: TextStyle(fontSize: 12, color: Colors.grey.shade600)),
                      ],
                    ),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                decoration: BoxDecoration(
                  color: pillBg,
                  borderRadius: BorderRadius.circular(20),
                ),
                child: Row(
                  children: [
                    Container(
                      width: 6,
                      height: 6,
                      decoration: BoxDecoration(
                        color: pillText,
                        shape: BoxShape.circle,
                      ),
                    ),
                    const SizedBox(width: 6),
                    Text(
                      statusLabel,
                      style: TextStyle(
                        fontSize: 12,
                        fontWeight: FontWeight.bold,
                        color: pillText,
                      ),
                    ),
                  ],
                ),
              ),
              Row(
                children: [
                  GestureDetector(
                    onTap: () {
                      final bId = (_bookingData?['booking_id'] ?? _bookingData?['display_id'] ?? widget.bookingId ?? _bookingData?['_id'])?.toString();
                      if (bId != null && bId.isNotEmpty) {
                        Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (context) => CustomerChatScreen(
                              bookingId: bId,
                              providerName: name,
                            ),
                          ),
                        );
                      }
                    },
                    child: Container(
                      padding: const EdgeInsets.all(8),
                      decoration: const BoxDecoration(
                        color: Color(0xFFEFF1FE),
                        shape: BoxShape.circle,
                      ),
                      child: const Icon(Icons.chat_bubble_outline_rounded, color: Color(0xFF1B1464), size: 18),
                    ),
                  ),
                  const SizedBox(width: 10),
                  GestureDetector(
                    onTap: () => _makePhoneCall(phone),
                    child: Container(
                      padding: const EdgeInsets.all(8),
                      decoration: const BoxDecoration(
                        color: Color(0xFF1B1464),
                        shape: BoxShape.circle,
                      ),
                      child: const Icon(Icons.call, color: Colors.white, size: 18),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildTimeline({
    required int currentStep,
    required String status,
    String? startOtp,
    String? endOtp,
  }) {
    final bool showStartOtpBox = (status == 'arrived' || status == 'waiting_start_otp');
    final bool showEndOtpBox = (status == 'waiting_end_otp');

    final bookingCode = _bookingData?['booking_id']?.toString() ?? _bookingData?['_id']?.toString() ?? '';

    return ListView(
      shrinkWrap: true,
      physics: const NeverScrollableScrollPhysics(),
      children: [
        _buildTimelineItem(
          index: 0,
          currentStep: currentStep,
          status: status,
          title: 'Booking Placed',
          subtitle: bookingCode.isNotEmpty ? 'Order confirmed (Ref: $bookingCode)' : 'Order confirmed successfully',
          isLast: false,
        ),
        _buildTimelineItem(
          index: 1,
          currentStep: currentStep,
          status: status,
          title: 'Professional Assigned',
          subtitle: currentStep >= 1 ? 'Provider has accepted your booking' : 'Searching for professional...',
          isLast: false,
        ),
        _buildTimelineItem(
          index: 2,
          currentStep: currentStep,
          status: status,
          title: 'Professional On The Way',
          subtitle: currentStep >= 2 ? 'Provider is traveling to your location' : 'Waiting for provider movement',
          isLast: false,
        ),
        _buildTimelineItem(
          index: 3,
          currentStep: currentStep,
          status: status,
          title: 'Professional Arrived & Start Service',
          subtitle: showStartOtpBox
              ? 'Share this Start OTP with the professional upon arrival'
              : (currentStep > 3 ? 'Start OTP Verified' : 'OTP generated when provider arrives'),
          isLast: false,
          child: showStartOtpBox
              ? _buildOtpBox(
                  otp: startOtp,
                  helperText: 'Provide this Start OTP to the professional to begin service.',
                )
              : null,
        ),
        _buildTimelineItem(
          index: 4,
          currentStep: currentStep,
          status: status,
          title: 'Service In Progress',
          subtitle: currentStep >= 4 ? 'Professional is executing your service' : 'Pending service start',
          isLast: false,
        ),
        _buildTimelineItem(
          index: 5,
          currentStep: currentStep,
          status: status,
          title: 'Service Completion Verification',
          subtitle: showEndOtpBox
              ? 'Share this End OTP with the professional to finish service'
              : (currentStep > 5 ? 'End OTP Verified' : 'OTP generated when service ends'),
          isLast: false,
          child: showEndOtpBox
              ? _buildOtpBox(
                  otp: endOtp ?? _bookingData?['endOtp'] ?? _bookingData?['completionOtp'],
                  helperText: 'Provide this End OTP ONLY after service is completed satisfactorily.',
                  isEndOtp: true,
                  bookingId: (widget.bookingId ?? _bookingData?['_id'] ?? _bookingData?['id'])?.toString(),
                )
              : null,
        ),
        _buildTimelineItem(
          index: 6,
          currentStep: currentStep,
          status: status,
          title: 'Service Completed',
          subtitle: status == 'completed' ? 'Service fulfilled successfully' : 'Final step',
          isLast: true,
        ),
      ],
    );
  }

  Widget _buildOtpBox({
    required String? otp,
    required String helperText,
    bool isEndOtp = false,
    String? bookingId,
  }) {
    final String formattedOtp = (otp != null && otp.length == 6)
        ? '${otp[0]}  ${otp[1]}  ${otp[2]}  ${otp[3]}  ${otp[4]}  ${otp[5]}'
        : (otp ?? 'Waiting for OTP...');

    return Container(
      margin: const EdgeInsets.only(top: 12, bottom: 8),
      padding: const EdgeInsets.all(16),
      width: double.infinity,
      decoration: BoxDecoration(
        color: Colors.white,
        border: Border.all(color: const Color(0xFF1B1464).withOpacity(0.3), width: 1.5),
        borderRadius: BorderRadius.circular(12),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.04),
            blurRadius: 6,
            offset: const Offset(0, 3),
          ),
        ],
      ),
      child: Column(
        children: [
          Text(
            formattedOtp,
            style: const TextStyle(
              fontSize: 26,
              fontWeight: FontWeight.bold,
              color: Color(0xFF1B1464),
              letterSpacing: 4.0,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            helperText,
            textAlign: TextAlign.center,
            style: TextStyle(
              fontSize: 11,
              color: Colors.grey.shade600,
              fontWeight: FontWeight.w500,
            ),
          ),
          if (isEndOtp && bookingId != null) ...[
            const SizedBox(height: 12),
            OutlinedButton.icon(
              style: OutlinedButton.styleFrom(
                foregroundColor: const Color(0xFF1B1464),
                side: const BorderSide(color: Color(0xFF1B1464)),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
              ),
              icon: const Icon(Icons.send_to_mobile, size: 16),
              label: const Text('Resend Completion OTP to SMS', style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold)),
              onPressed: () async {
                final res = await ApiService.resendCompletionOtp(bookingId);
                if (mounted) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(
                      content: Text(res['message'] ?? 'Resent completion OTP!'),
                      backgroundColor: res['success'] == true ? Colors.green : Colors.red,
                    ),
                  );
                }
              },
            ),
          ],
        ],
      ),
    );
  }


  Widget _buildTimelineItem({
    required int index,
    required int currentStep,
    required String status,
    required String title,
    required String subtitle,
    required bool isLast,
    Widget? child,
  }) {
    bool isCompleted = index < currentStep || (status == 'completed' && index <= currentStep);
    bool isActive = index == currentStep && status != 'completed';

    Color lineColor = isCompleted ? const Color(0xFF1B1464) : Colors.grey.shade200;
    Color titleColor = isCompleted || isActive ? Colors.black87 : Colors.grey.shade400;
    Color subtitleColor = isCompleted || isActive ? Colors.grey.shade600 : Colors.grey.shade400;

    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Column(
          children: [
            Container(
              width: 24,
              height: 24,
              decoration: BoxDecoration(
                color: isCompleted ? const Color(0xFF1B1464) : (isActive ? Colors.white : Colors.grey.shade300),
                shape: BoxShape.circle,
                border: Border.all(
                  color: isActive ? const Color(0xFF1B1464) : Colors.transparent,
                  width: 2,
                ),
              ),
              child: isCompleted
                  ? const Icon(Icons.check, size: 14, color: Colors.white)
                  : (isActive
                      ? Center(
                          child: Container(
                            width: 8,
                            height: 8,
                            decoration: const BoxDecoration(
                              color: Color(0xFF1B1464),
                              shape: BoxShape.circle,
                            ),
                          ),
                        )
                      : null),
            ),
            if (!isLast)
              Container(
                width: 2,
                height: child != null ? 100 : 48,
                color: lineColor,
              ),
          ],
        ),
        const SizedBox(width: 12),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                title,
                style: TextStyle(
                  fontSize: 15,
                  fontWeight: FontWeight.bold,
                  color: titleColor,
                ),
              ),
              if (subtitle.isNotEmpty) ...[
                const SizedBox(height: 2),
                Text(
                  subtitle,
                  style: TextStyle(
                    fontSize: 12,
                    color: subtitleColor,
                  ),
                ),
              ],
              if (child != null) child,
              const SizedBox(height: 16),
            ],
          ),
        ),
      ],
    );
  }
}
